### ISSUE TITLE
AddPicture Method Not Respecting AutoFit and LockAspectRatio in GraphicOptions

### ISSUE THREAD

**Issue by t4traw** [qax-os/excelize#1536]
**Description**

I'm experiencing an issue with the `AddPicture` method in the `excelize` package. Despite setting `AutoFit` to `true` and `LockAspectRatio` to `true` in `GraphicOptions`, it seems that the aspect ratio is only respected in the vertical direction, not in the horizontal direction. As a result, the images are distorted and do not fit correctly within the cells.

Here's the relevant part of my code:

```go
package main

import (
	_ "image/jpeg"

	"github.com/xuri/excelize/v2"
)

func main() {
	xlsx, _ := excelize.OpenFile("base.xlsx")
	pos, _ := xlsx.SearchSheet("Sheet1", "[photo]")
	graphicOptions := excelize.GraphicOptions{
		AutoFit:         true,
		LockAspectRatio: true,
	}
	xlsx.AddPicture("Sheet1", pos[0], "400x300.jpg", &graphicOptions)
	xlsx.SaveAs("output.xlsx")
}
```

**Describe the results you received:**

### file: base.xlsx

<img width="298" alt="bug_sample" src="https://user-images.githubusercontent.com/6788936/235039028-472681de-bccd-481b-b6df-60bd2a30b131.png">

### file: output.xlsx

<img width="283" alt="output" src="https://user-images.githubusercontent.com/6788936/235039182-d94bb892-8835-478f-82e3-f76e30202142.png">

**Output of `go version`:**

```text
go version go1.19 darwin/arm64
```

**Excelize version or commit ID:**

```text
2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

- OS: macOS 13.3.1
- Excel: 16.72

Any help on this issue would be greatly appreciated. Thank you!

**Comment by xuri** [comment]
Hi @t4traw, thanks for your issue. I have tested with your code and it seems works well. Could you provide the base.xlsx and 400x300.jpg as a attachments?

**Comment by xuri** [comment]
Hi @yamato1413, thanks for your feedback. The problem as your mentions was related to the issues #260, #279, #569 and #1419.

**Comment by t4traw** [comment]
@xuri Thank you for response! I'm sending a zip of the code tested in my environment along with the output results (also, I've created a repository for it https://github.com/t4traw/excelize_addPicture_sample).
Thank you for such a wonderful library!

[sample.zip](https://github.com/qax-os/excelize/files/11503848/sample.zip)

**Comment by xuri** [comment]
Thanks for your feedback. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by t4traw** [comment]
@xuri Thank you! I'm looking forward to the v2.8.0!

**Comment by t4traw** [comment]
@xuri I immediately tried out the commit contents of the master branch! It seems better than before, but it still appears the scale value is off. I've attached the re-output results as a zip file.

[sample_ 08ba272.zip](https://github.com/qax-os/excelize/files/11513382/sample_.08ba272.zip)

![export_image](https://github.com/qax-os/excelize/assets/6788936/cd5596b9-4273-4019-be2e-99a30acc34bf)

**Comment by xuri** [comment]
Thanks for your feedback. I changed the default point to the pixels conversion factor for a better scale effect. But we still can't get the exact scaling percentage, related to I replies in issue #569, the image scaling depends on each row's height and column's width, these storage inner workbook files with pt units, we need to covert it into pixels, since this conversion was effected by device DPI, so we can't be made the conversion result fit any devices. As you open the same workbook with an image in a difference spreadsheet application, operation system, or client device, the size of an image may be different, so please adjust the scale by image options as you need.
