### ISSUE TITLE
Found a defect in the FIND function during the process of multi-value query.

### ISSUE THREAD

**Issue by podmask** [qax-os/excelize#1819]
**Description**

```
func TestMyTest(t *testing.T) {
	f, err := excelize.OpenFile("../test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()
	f.SetCellValue("sheet1", "D2", "张三")
	f.SetCellFormula("sheet1", "B2", `OR(ISNUMBER(FIND({"王五","李四","张三","陈七","刘大"},D2)))`)
	value, err := f.CalcCellValue("sheet1", "B2")
	if err != nil {
		fmt.Println("ERROR:", err)
		return
	}
	t.Log("value is:", value)
}

```

**Steps to reproduce the issue:**
1. Run this test.

**Describe the results you received:**
```
=== RUN   TestMyTest
    d:\DEV\go-dev\excelizer\testing\excel_test.go:99: value is: FALSE
--- PASS: TestMyTest (0.01s)
PASS
ok  	excelizer/testing	0.271s
```
**Describe the results you expected:**

```
=== RUN   TestMyTest
    d:\DEV\go-dev\excelizer\testing\excel_test.go:99: value is: TRUE
--- PASS: TestMyTest (0.01s)
PASS
ok  	excelizer/testing	0.271s

```
**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**
WPS 
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this, and this patch has been released on v2.8.1, please upgrade to the lasted version.

**Comment by podmask** [comment]
Thank you for your attention to this issue. I have updated to version v2.8.1 following your guidance, but the result of the unit test is still "FALSE". Could you please confirm if your test environment has passed this test?

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed. Please try to upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by podmask** [comment]
Thank you very much for fixing this bug. In the latest master version, the above issue returns the correct result; however, the code still does not work properly under the following circumstances:

func TestMyTest(t *testing.T) {
	f, err := excelize.OpenFile("../test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()
	f.SetCellValue("sheet1", "D2", "张三丰")
	f.SetCellFormula("sheet1", "B2", `IF(ISNUMBER(FIND({"王五","李四","张三","陈七","刘大"},D2)),"TRUE","FALSE")`)
	value, err := f.CalcCellValue("sheet1", "B2")
	if err != nil {
		fmt.Println("ERROR:", err)
		return
	}
	t.Log("value is:", value)
}

**the results I received:**
`
Running tool: D:\golang\go\bin\go.exe test -timeout 30s -run ^TestMyTest$ excelizer/testing -v

=== RUN   TestMyTest
    d:\DEV\excelizer\testing\excel_test.go:99: value is: FALSE
--- PASS: TestMyTest (0.01s)
PASS
ok  	excelizer/testing	
`

**the results I expected:**
`
Running tool: D:\golang\go\bin\go.exe test -timeout 30s -run ^TestMyTest$ excelizer/testing -v

=== RUN   TestMyTest
    d:\DEV\excelizer\testing\excel_test.go:99: value is: TRUE
--- PASS: TestMyTest (0.01s)
PASS
ok  	excelizer/testing	
`

**Comment by xuri** [comment]
Thanks for your feedback. Could you provide the `test.xlsx` in your example? I created a new workbook instead of opening an existing workbook name. Because the value `张三丰` was not in the `FIND` formula's first argument array, the result of the `ISNUMBER` function should be `FALSE`. So, the calculated result is expected, which be the same as the calculated result in the spreadsheet app.
