### ISSUE TITLE
OOM when GetMergeCells on linux

### ISSUE THREAD

**Issue by sqdtss** [qax-os/excelize#2226]
### Description

When I open the xlsx file below and call the GetMergeCells method on a linux machine, it will be out of memory(OOM).
We have encountered several such cases and would like to ask how to retrieve merged cell information with low CPU and memory usage.
[test.xlsx](https://github.com/user-attachments/files/23093989/test.xlsx)

### Steps to reproduce the issue

Open the file and call the GetMergeCells method on a linux machine.
```go
file, err := excelize.OpenFile("test.xlsx", excelize.Options{})
if err != nil {
	fmt.Println(err)
	return
}
defer func() {
	if err = file.Close(); err != nil {
		fmt.Println(err)
	}
}()
for _, sheet := range file.GetSheetList() {
	mergeCells, err := file.GetMergeCells(sheet)
	if err != nil {
		fmt.Println("GetMergeCells err:", err)
		return
	}
}
```

### Describe the results you received

The machine will be out of memory.

### Describe the results you expected

The result can be retrieved with low CPU and memory usage.

### Go version

1.23.0

### Excelize version or commit ID

2.9.1

### Environment

linux with 16 core and 80G memory.

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been resolved, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by sqdtss** [comment]
> Thanks for your feedback. This issue has been resolved, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

Thanks for your attention! I have tried the latest master, but I found that the problem still exists. Do I need to do any configs to limit the memory?
<img width="1112" height="554" alt="Image" src="https://github.com/user-attachments/assets/a2bed4fa-47c3-4960-ad55-320c7f7d7cf9" />

**Comment by xuri** [comment]
Please make sure you're using the master branch code. I've tested with following code and it work well:


```go
package main

import (
	"fmt"
	"runtime"
	"syscall"
	"time"

	"github.com/xuri/excelize/v2"
)

func main() {
	runtime.GC()
	startTime := time.Now()
	file, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		if err = file.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	for _, sheet := range file.GetSheetList() {
		mergeCells, err := file.GetMergeCells(sheet)
		if err != nil {
			fmt.Println("GetMergeCells err:", err)
			return
		}
		fmt.Sprintf("%s has %d merged cells\r\n", sheet, len(mergeCells))
	}
	printBenchmarkInfo("resource usage:", startTime)
}

func printBenchmarkInfo(fn string, startTime time.Time) {
	var memStats runtime.MemStats
	var rusage syscall.Rusage
	var bToMb = func(b uint64) uint64 {
		return b / 1024 / 1024
	}
	runtime.ReadMemStats(&memStats)
	syscall.Getrusage(syscall.RUSAGE_SELF, &rusage)
	fmt.Printf("Func: %s \tRSS = %v MB\tAlloc = %v MB\tTotalAlloc = %v MB\tSys = %v MB\tNumGC = %v \tCost = %s\n",
		fn, bToMb(uint64(rusage.Maxrss)), bToMb(memStats.Alloc), bToMb(memStats.TotalAlloc), bToMb(memStats.Sys), memStats.NumGC, time. Since(startTime))
}
```

Output:


```text
Func: resource usage: RSS = 0 MB  Alloc = 1 MB  TotalAlloc = 2 MB  Sys = 8 MB  NumGC = 1  Cost = 3.411209ms
```

**Comment by sqdtss** [comment]
> Please make sure you're using the master branch code. I've tested with following code and it work well:
> 
> package main
> 
> import (
> 	"fmt"
> 	"runtime"
> 	"syscall"
> 	"time"
> 
> 	"github.com/xuri/excelize/v2"
> )
> 
> func main() {
> 	runtime.GC()
> 	startTime := time.Now()
> 	file, err := excelize.OpenFile("test.xlsx")
> 	if err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 	defer func() {
> 		if err = file.Close(); err != nil {
> 			fmt.Println(err)
> 		}
> 	}()
> 	for _, sheet := range file.GetSheetList() {
> 		mergeCells, err := file.GetMergeCells(sheet)
> 		if err != nil {
> 			fmt.Println("GetMergeCells err:", err)
> 			return
> 		}
> 		fmt.Sprintf("%s has %d merged cells\r\n", sheet, len(mergeCells))
> 	}
> 	printBenchmarkInfo("resource usage:", startTime)
> }
> 
> func printBenchmarkInfo(fn string, startTime time.Time) {
> 	var memStats runtime.MemStats
> 	var rusage syscall.Rusage
> 	var bToMb = func(b uint64) uint64 {
> 		return b / 1024 / 1024
> 	}
> 	runtime.ReadMemStats(&memStats)
> 	syscall.Getrusage(syscall.RUSAGE_SELF, &rusage)
> 	fmt.Printf("Func: %s \tRSS = %v MB\tAlloc = %v MB\tTotalAlloc = %v MB\tSys = %v MB\tNumGC = %v \tCost = %s\n",
> 		fn, bToMb(uint64(rusage.Maxrss)), bToMb(memStats.Alloc), bToMb(memStats.TotalAlloc), bToMb(memStats.Sys), memStats.NumGC, time. Since(startTime))
> }
> Output:
> 
> ```
> Func: resource usage: RSS = 0 MB  Alloc = 1 MB  TotalAlloc = 2 MB  Sys = 8 MB  NumGC = 1  Cost = 3.411209ms
> ```

Thanks very much, it truly worked.
